### PR TITLE
feat: add `Uniplate::holes` and `Uniplate::contexts`

### PR DESCRIPTION
**Pull request by niklasdewally**
Port `holes` and `context` functions from the original Haskell library.

### CODE REVIEW

**Comment by niklasdewally** [comment]
@ozgurakgun would appreciate a sanity check for this.

**Review by ozgurakgun — APPROVED** [review]
Looks good! What's left before we have full zippers then? Now that we have holes and contexts, I think it's just the traversal functions, isn't it?

**Comment by niklasdewally** [comment]
> Looks good! What's left before we have full zippers then? Now that we have holes and contexts, I think it's just the traversal functions, isn't it?

Yep!

**Comment by ozgurakgun** [comment]
I only checked in my phone without running anything btw. One thing this made me think is whether we want iterators instead of vectors for some of the other functions too.

We never did performance profiling so hard to know.

**Comment by niklasdewally** [comment]
> I only checked in my phone without running anything btw. One thing this made me think is whether we want iterators instead of vectors for some of the other functions too.

Thats the long-term goal. Still not sure whether to make the default operations return an iterator, or have a seperate iterator API though!

Also, the internal `tree` datastructure is not lazy yet...

**Pull request merged**
